export type DirectorySector = { code: string; name: string; subcategories: string[] };

const split = (value: string) => value.split('|').map((item) => item.trim()).filter(Boolean);

export const DIRECTORY_SECTORS: DirectorySector[] = [
  { code: 'AGR', name: 'Agriculture - Élevage', subcategories: split('Agriculture, fermes & plantations|Élevage|Intrants agricoles|Semences & plants|Engrais & fertilisants|Produits phytosanitaires|Équipements agricoles|Irrigation & pompage|Aliments pour animaux|Produits vétérinaires|Cliniques vétérinaires|Matériel d’élevage|Transformation agricole') },
  { code: 'ALI', name: 'Alimentation & Boissons', subcategories: split('Produits alimentaires|Produits laitiers|Boucheries & charcuteries|Boulangeries & pâtisseries|Boissons & eaux|Supermarchés|Grossistes alimentaires|Produits frais|Restauration collective') },
  { code: 'BAN', name: 'Banques - Finances - Assurances', subcategories: split('Banques|Microfinance|Crédit|Transfert d’argent|Paiement électronique|Fintech|Assurances|Audit|Expertise comptable|Conseil financier|Services fiscaux') },
  { code: 'COM', name: 'Boutiques - Commerce - Shopping', subcategories: split('Habillement|Chaussures|Mode & accessoires|Coiffure & esthétique|Articles de sport|Cadeaux & fleurs|Optique & lunettes|Mobilier & décoration|Électroménager|TV, audio & Hi-Fi|Éclairage & luminaires|Centres commerciaux|Art & galeries') },
  { code: 'ICT', name: 'Bureautique - Informatique - Télécoms', subcategories: split('Ordinateurs|Serveurs|Imprimantes & scanners|Photocopieurs|Fournitures de bureau|Logiciels|Développement informatique|Solutions cloud|Cybersécurité|Réseaux informatiques|Téléphonie mobile|Télécommunications|Fournisseurs Internet|Maintenance informatique|Accessoires informatiques') },
  { code: 'BTP', name: 'Construction - Bâtiment - Travaux publics', subcategories: split('Construction générale|Génie civil|Routes & voiries|Ponts|Terrassement|Architecture|Bureaux d’études|Matériaux de construction|Ciment|Fer & acier|Quincaillerie|Plomberie|Électricité bâtiment|Peinture|Menuiserie|Climatisation|Toiture|Carrelage|Location d’engins|Assainissement') },
  { code: 'ENE', name: 'Énergie - Électricité - Carburants', subcategories: split('Électricité|Groupes électrogènes|Énergie solaire|Panneaux solaires|Batteries|Onduleurs|Transformateurs|Installations électriques|Carburants|Lubrifiants|Stations-service|Gaz|Énergies renouvelables|Maintenance énergétique') },
  { code: 'EQU', name: 'Équipements pour entreprises', subcategories: split('Mobilier de bureau|Machines professionnelles|Équipements industriels|Matériel de manutention|Rayonnages|Équipements de nettoyage|Équipements de cuisine professionnelle|Climatisation|Uniformes & EPI|Matériel de stockage|Pièces détachées') },
  { code: 'HOT', name: 'Hôtels - Restaurants - Hébergement', subcategories: split('Hôtels|Appart-hôtels|Résidences|Restaurants|Bars|Cafés|Traiteurs|Catering|Salles de réception|Location de salles|Équipements hôteliers|Fournitures pour hôtels & restaurants') },
  { code: 'IMP', name: 'Import - Export - Distribution', subcategories: split('Importateurs|Exportateurs|Grossistes|Distributeurs|Représentants de marques|Centrales d’achat|Commerce général|Transit|Douane|Entreposage|Chaîne logistique|Distribution spécialisée') },
  { code: 'IND', name: 'Industries - Manufactures', subcategories: split('Agro-industrie|Industrie alimentaire|Textile|Plastique|Métallurgie|Bois|Papier & emballage|Imprimerie|Produits chimiques|Fabrication de meubles|Assemblage|Machines & équipements|Conditionnement') },
  { code: 'TOU', name: 'Loisirs - Sport - Tourisme', subcategories: split('Agences de voyages|Tourisme|Hôtels touristiques|Location de véhicules|Clubs sportifs|Salles de sport|Équipements sportifs|Événementiel|Loisirs|Culture|Arts|Billetterie') },
  { code: 'MIN', name: 'Mines - Carrières', subcategories: split('Exploitation minière|Exploration|Carrières|Géologie|Forage|Laboratoires miniers|Équipements miniers|Engins lourds|Pièces détachées|Transport minier|Sécurité minière|Sous-traitance minière|Services environnementaux') },
  { code: 'MAR', name: 'Publicité - Marketing - Communication', subcategories: split('Agences marketing|Publicité|Communication|Marketing digital|Réseaux sociaux|Impression|Enseignes|Branding|Graphisme|Production audiovisuelle|Photographie|Relations publiques|Événementiel|Objets publicitaires') },
  { code: 'SAN', name: 'Santé - Médecine - Pharmacie', subcategories: split('Hôpitaux|Cliniques|Centres médicaux|Médecins|Pharmacies|Laboratoires|Imagerie médicale|Matériel médical|Consommables médicaux|Produits pharmaceutiques|Ambulances|Dentistes|Opticiens|Médecine du travail') },
  { code: 'SEC', name: 'Sécurité - Gardiennage - Protection', subcategories: split('Gardiennage|Sécurité privée|Surveillance|Vidéosurveillance|Alarmes|Contrôle d’accès|Sécurité incendie|Extincteurs|Équipements de protection|Géolocalisation|Sécurité électronique|Formation sécurité') },
  { code: 'SER', name: 'Services aux entreprises', subcategories: split('Conseil|Assistance administrative|Ressources humaines|Recrutement|Formation|Juridique|Avocats|Comptabilité|Audit|Fiscalité|Traduction|Nettoyage professionnel|Maintenance|Facility management|Externalisation|Secrétariat|Archivage|Gestion documentaire') },
  { code: 'FUN', name: 'Services funéraires', subcategories: split('Pompes funèbres|Morgues|Cercueils|Transport funéraire|Chambres funéraires|Organisation des obsèques|Fleurs & décoration funéraire|Cimetières|Services administratifs funéraires') },
  { code: 'TRA', name: 'Transport - Logistique - Air - Route - Mer', subcategories: split('Transport routier|Transport aérien|Transport maritime|Fret|Logistique|Livraison|Messagerie|Courrier express|Transit|Dédouanement|Location de camions|Location de véhicules|Transport du personnel|Transport de marchandises|Entrepôts') },
  { code: 'EDU', name: 'Éducation - Formation', subcategories: split('Écoles|Universités|Instituts|Centres de formation|Formation professionnelle|Formation informatique|Formation en entreprise|E-learning|Fournitures scolaires|Matériel pédagogique') },
  { code: 'IMM', name: 'Immobilier - Gestion immobilière', subcategories: split('Agences immobilières|Vente immobilière|Location|Gestion immobilière|Promotion immobilière|Terrains|Bureaux|Entrepôts|Expertise immobilière|Facility management') },
  { code: 'EAU', name: 'Eau - Assainissement - Environnement', subcategories: split('Distribution d’eau|Forage|Traitement d’eau|Pompage|Assainissement|Gestion des déchets|Recyclage|Nettoyage industriel|Études environnementales|Équipements sanitaires') },
  { code: 'AUT', name: 'Automobile - Engins - Pièces détachées', subcategories: split('Véhicules neufs|Véhicules d’occasion|Pièces détachées|Pneus|Batteries|Garages|Entretien automobile|Carrosserie|Location de véhicules|Engins lourds|Motos|Lubrifiants') },
  { code: 'JUR', name: 'Juridique - Conseil - Expertise', subcategories: split('Cabinets d’avocats|Conseillers juridiques|Notaires|Huissiers|Médiation|Arbitrage|Propriété intellectuelle|Conseil fiscal|Expertise|Recouvrement') },
  { code: 'NET', name: 'Nettoyage - Entretien - Hygiène', subcategories: split('Nettoyage de bureaux|Nettoyage industriel|Désinfection|Désinsectisation|Dératisation|Blanchisserie|Produits d’entretien|Collecte des déchets|Entretien d’espaces verts') },
];
