import type {
  DocDocument,
  KPIData,
  DepartmentPerformance,
  AssistantMessage,
  Task,
  Dossier,
  Project,
  Report,
  TeamMember,
  RolePermission,
  EscalationRule,
  RFQ,
  RFQTemplate,
  Company,
  Partner,
  Opportunity,
} from './types';

export const kpiData: KPIData = {
  total: 286,
  processed: 241,
  inProgress: 27,
  overdue: 18,
  avgProcessingDays: 3.4,
  onTimeRate: 87,
};

export const departmentPerformance: DepartmentPerformance[] = [
  { department: 'Comptabilité', total: 94, processed: 82, overdue: 5, avgDays: 2.8 },
  { department: 'Administration', total: 67, processed: 58, overdue: 4, avgDays: 3.1 },
  { department: 'Juridique', total: 43, processed: 34, overdue: 6, avgDays: 5.2 },
  { department: 'Commercial', total: 52, processed: 47, overdue: 2, avgDays: 2.1 },
  { department: 'Opérations', total: 30, processed: 20, overdue: 1, avgDays: 4.0 },
];

export const documents: DocDocument[] = [
  {
    id: 'd001',
    reference: 'INV-2026-0847',
    title: 'Facture — Fournitures bureau Q3',
    type: 'invoice',
    status: 'in_review',
    priority: 'high',
    sender: { name: 'TechnoSupply SARL', type: 'supplier', avatarColor: 'bg-primary-600' },
    recipient: { name: 'Direction Finance', type: 'internal', avatarColor: 'bg-accent-600' },
    amount: 12500,
    currency: 'USD',
    receivedDate: '2026-09-04',
    dueDate: '2026-09-30',
    aiSummary:
      "Facture de TechnoSupply SARL pour les fournitures de bureau du troisième trimestre. Le montant total s'élève à 12 500 USD avec une échéance au 30 septembre 2026. Une remise commerciale de 5% a été appliquée. Le document référence le bon de commande PO-2026-0312.",
    aiKeyPoints: [
      'Montant TTC : 12 500 USD',
      'Échéance : 30 septembre 2026',
      'Bon de commande référencé : PO-2026-0312',
      'Remise commerciale 5% incluse',
      'TVA applicable 20%',
    ],
    aiAmount: 12500,
    aiDueDate: '2026-09-30',
    aiConfidence: 96,
    aiSuggestedDepartment: 'Comptabilité',
    aiSuggestedAction: 'Vérifier la conformité avec le bon de commande et préparer le paiement.',
    assignedTo: 'Marie Dubois',
    assignedDepartment: 'Comptabilité',
    pages: 3,
    hasPhysicalOriginal: true,
    physicalStatus: 'in_transit',
    category: 'Facture fournisseur',
    tags: ['facture', 'fournisseur', 'Q3', 'urgent'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0142',
    dossierId: 'dos001',
    collaboration: [
      {
        id: 'm1',
        author: 'Marie Dubois',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message:
          'Le montant ne correspond pas au bon de commande PO-2026-0312. Il y a un écart de 625 USD.',
        timestamp: '2026-09-04 14:23',
      },
      {
        id: 'm2',
        author: 'Karim Benali',
        authorRole: 'supplier',
        avatarColor: 'bg-primary-600',
        message:
          'Nous venons de joindre le bon de livraison BL-7821 qui justifie la remise commerciale additionnelle.',
        timestamp: '2026-09-04 15:47',
        attachments: [{ name: 'BL-7821.pdf', type: 'pdf' }],
      },
      {
        id: 'm3',
        author: 'Marie Dubois',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message: 'Document reçu. Nous transmettons à la comptabilité pour validation.',
        timestamp: '2026-09-05 09:12',
      },
    ],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-04 11:02', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Marie Dubois (Comptabilité)', actor: 'Auto-assignation', timestamp: '2026-09-04 11:05', icon: 'assign' },
      { id: 'a3', action: 'Échéance détectée : 30 sept. 2026', actor: 'Système IA', timestamp: '2026-09-04 11:02', icon: 'alert' },
      { id: 'a4', action: 'Discussion ouverte avec le fournisseur', actor: 'Marie Dubois', timestamp: '2026-09-04 14:23', icon: 'comment' },
    ],
    processingTime: 2.1,
  },
  {
    id: 'd002',
    reference: 'CTR-2026-0034',
    title: 'Contrat de prestation — Conseil stratégique',
    type: 'contract',
    status: 'assigned',
    priority: 'urgent',
    sender: { name: 'Cabinet Leroy & Associés', type: 'partner', avatarColor: 'bg-warning-600' },
    recipient: { name: 'Direction Générale', type: 'internal', avatarColor: 'bg-ink-700' },
    receivedDate: '2026-09-05',
    dueDate: '2026-09-10',
    aiSummary:
      "Contrat de prestation de conseil stratégique proposé par le Cabinet Leroy & Associés. Durée de 12 mois, renouvelable tacitement. Montant annuel de 85 000 EUR. Clause de résiliation avec préavis de 3 mois. Le contrat inclut une clause de confidentialité renforcée et une exclusivité sectorielle.",
    aiKeyPoints: [
      'Durée : 12 mois renouvelable',
      'Montant annuel : 85 000 EUR',
      'Préavis de résiliation : 3 mois',
      'Clause de confidentialité renforcée',
      'Exclusivité sectorielle incluse',
      'Signature requise avant le 10 septembre',
    ],
    aiAmount: 85000,
    aiDueDate: '2026-09-10',
    aiConfidence: 94,
    aiSuggestedDepartment: 'Juridique',
    aiSuggestedAction: 'Revoir les clauses et préparer la signature pour le 10 septembre.',
    assignedTo: 'Sophie Martin',
    assignedDepartment: 'Juridique',
    pages: 18,
    hasPhysicalOriginal: true,
    physicalStatus: 'in_transit',
    category: 'Contrat',
    tags: ['contrat', 'juridique', 'urgent', 'signature'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0143',
    dossierId: 'dos002',
    collaboration: [
      {
        id: 'm1',
        author: 'Sophie Martin',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message:
          'La clause d\'exclusivité sectorielle semble trop large. Peut-on la limiter à notre secteur principal ?',
        timestamp: '2026-09-05 10:30',
      },
    ],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-05 09:15', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Sophie Martin (Juridique)', actor: 'Auto-assignation', timestamp: '2026-09-05 09:18', icon: 'assign' },
      { id: 'a3', action: 'Échéance critique : 10 sept. 2026', actor: 'Système IA', timestamp: '2026-09-05 09:15', icon: 'alert' },
    ],
    processingTime: 1.2,
  },
  {
    id: 'd003',
    reference: 'LTR-2026-0212',
    title: 'Courrier — Mise en demeure client Apex',
    type: 'letter',
    status: 'overdue',
    priority: 'urgent',
    sender: { name: 'Apex Industries', type: 'client', avatarColor: 'bg-danger-600' },
    recipient: { name: 'Service Recouvrement', type: 'internal', avatarColor: 'bg-warning-600' },
    receivedDate: '2026-08-20',
    dueDate: '2026-08-30',
    aiSummary:
      "Mise en demeure adressée par Apex Industries concernant un retard de paiement de 34 200 EUR. Le courrier exige un règlement sous 8 jours à compter de la réception, faute de quoi une procédure judiciaire sera engagée. Des pénalités de retard de 1,5% par mois sont réclamées.",
    aiKeyPoints: [
      'Montant réclamé : 34 200 EUR',
      'Délai exigé : 8 jours',
      'Pénalités de retard : 1,5%/mois',
      'Menace de procédure judiciaire',
      'Courrier en retard de traitement',
    ],
    aiAmount: 34200,
    aiDueDate: '2026-08-30',
    aiConfidence: 92,
    aiSuggestedDepartment: 'Juridique',
    aiSuggestedAction: 'Contacter Apex Industries immédiatement et négocier un échéancier.',
    assignedTo: 'Thomas Leroy',
    assignedDepartment: 'Juridique',
    pages: 2,
    hasPhysicalOriginal: true,
    physicalStatus: 'delivered',
    category: 'Courrier officiel',
    tags: ['courrier', 'juridique', 'recouvrement', 'urgent', 'retard'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0128',
    dossierId: 'dos003',
    collaboration: [
      {
        id: 'm1',
        author: 'Thomas Leroy',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message:
          'Le délai est dépassé. Il faut contacter Apex Industries immédiatement pour négocier un échéancier.',
        timestamp: '2026-08-31 08:45',
      },
    ],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-08-20 14:00', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Thomas Leroy (Juridique)', actor: 'Auto-assignation', timestamp: '2026-08-20 14:05', icon: 'assign' },
      { id: 'a3', action: 'Échéance dépassée : 30 août 2026', actor: 'Système IA', timestamp: '2026-08-30 08:00', icon: 'alert' },
      { id: 'a4', action: 'Marqué en retard', actor: 'Système', timestamp: '2026-08-31 00:00', icon: 'alert' },
    ],
    processingTime: 17.5,
  },
  {
    id: 'd004',
    reference: 'RPT-2026-0089',
    title: 'Rapport mensuel — Activité commerciale août',
    type: 'report',
    status: 'validated',
    priority: 'normal',
    sender: { name: 'Service Commercial', type: 'internal', avatarColor: 'bg-accent-600' },
    recipient: { name: 'Direction Générale', type: 'internal', avatarColor: 'bg-ink-700' },
    receivedDate: '2026-09-01',
    dueDate: '2026-09-05',
    aiSummary:
      "Rapport d'activité commerciale du mois d'août 2026. Chiffre d'affaires de 1,2M EUR, en progression de 12% vs août 2025. 47 nouveaux contrats signés. Taux de conversion de 23%. Le rapport identifie 3 opportunités majeures pour le Q4 et recommande un renforcement de l'équipe Grand Comptes.",
    aiKeyPoints: [
      'CA : 1 200 000 EUR (+12% YoY)',
      '47 nouveaux contrats',
      'Taux de conversion : 23%',
      '3 opportunités identifiées pour le Q4',
      'Recommandation : renforcer l\'équipe Grand Comptes',
    ],
    aiConfidence: 91,
    aiSuggestedDepartment: 'Direction Générale',
    aiSuggestedAction: 'Intégrer au rapport consolidé mensuel de septembre.',
    assignedTo: 'Pierre Durand',
    assignedDepartment: 'Direction Générale',
    pages: 24,
    hasPhysicalOriginal: false,
    physicalStatus: 'not_required',
    category: 'Rapport interne',
    tags: ['rapport', 'commercial', 'mensuel', 'validé'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0135',
    projectId: 'proj001',
    collaboration: [],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-01 10:00', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Pierre Durand (DG)', actor: 'Auto-assignation', timestamp: '2026-09-01 10:02', icon: 'assign' },
      { id: 'a3', action: 'Validé par Pierre Durand', actor: 'Pierre Durand', timestamp: '2026-09-03 16:30', icon: 'validate' },
      { id: 'a4', action: 'Intégré au rapport consolidé', actor: 'Système IA', timestamp: '2026-09-03 16:35', icon: 'ai' },
    ],
    processingTime: 2.5,
  },
  {
    id: 'd005',
    reference: 'INV-2026-0848',
    title: 'Facture — Prestations informatiques août',
    type: 'invoice',
    status: 'received',
    priority: 'normal',
    sender: { name: 'CloudSystems Inc.', type: 'supplier', avatarColor: 'bg-primary-600' },
    recipient: { name: 'Direction IT', type: 'internal', avatarColor: 'bg-accent-600' },
    amount: 8750,
    currency: 'EUR',
    receivedDate: '2026-09-06',
    dueDate: '2026-10-06',
    aiSummary:
      "Facture de CloudSystems Inc. pour les prestations d'infrastructure cloud du mois d'août. Montant de 8 750 EUR, échéance au 6 octobre 2026. Inclut l'hébergement, la maintenance et le support premium. Référence le contrat-cadre CF-2025-007.",
    aiKeyPoints: [
      'Montant TTC : 8 750 EUR',
      'Échéance : 6 octobre 2026',
      'Contrat-cadre : CF-2025-007',
      'Hébergement + maintenance + support',
    ],
    aiAmount: 8750,
    aiDueDate: '2026-10-06',
    aiConfidence: 97,
    aiSuggestedDepartment: 'Direction IT',
    aiSuggestedAction: 'Vérifier la conformité des prestations et préparer le paiement.',
    pages: 2,
    hasPhysicalOriginal: false,
    physicalStatus: 'not_required',
    category: 'Facture fournisseur',
    tags: ['facture', 'IT', 'cloud', 'mensuel'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0144',
    collaboration: [],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-06 08:30', icon: 'ai' },
    ],
    processingTime: 0.2,
  },
  {
    id: 'd006',
    reference: 'ORD-2026-0156',
    title: 'Bon de commande — Équipements réseau',
    type: 'order',
    status: 'closed',
    priority: 'normal',
    sender: { name: 'Direction IT', type: 'internal', avatarColor: 'bg-accent-600' },
    recipient: { name: 'NetGear Pro', type: 'supplier', avatarColor: 'bg-primary-600' },
    amount: 23400,
    currency: 'EUR',
    receivedDate: '2026-08-15',
    dueDate: '2026-08-25',
    aiSummary:
      "Bon de commande pour l'acquisition d'équipements réseau : 12 commutateurs, 4 routeurs, et câblage associatif. Montant total de 23 400 EUR. Livraison demandée sous 10 jours. Garantie 3 ans incluse.",
    aiKeyPoints: [
      'Montant : 23 400 EUR',
      '12 commutateurs + 4 routeurs',
      'Livraison sous 10 jours',
      'Garantie 3 ans',
    ],
    aiAmount: 23400,
    aiDueDate: '2026-08-25',
    aiConfidence: 95,
    aiSuggestedDepartment: 'Opérations',
    aiSuggestedAction: 'Suivre la livraison et confirmer la réception des équipements.',
    assignedTo: 'Julie Chen',
    assignedDepartment: 'Opérations',
    pages: 5,
    hasPhysicalOriginal: false,
    physicalStatus: 'delivered',
    category: 'Bon de commande',
    tags: ['commande', 'IT', 'réseau', 'clôturé'],
    direction: 'outgoing',
    registerNumber: 'REG-S-2026-0089',
    dossierId: 'dos001',
    collaboration: [
      {
        id: 'm1',
        author: 'Julie Chen',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message: 'Commande reçue et testée. Tout est conforme.',
        timestamp: '2026-08-22 14:00',
      },
    ],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-08-15 09:00', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Julie Chen (Opérations)', actor: 'Auto-assignation', timestamp: '2026-08-15 09:03', icon: 'assign' },
      { id: 'a3', action: 'Livraison confirmée', actor: 'Julie Chen', timestamp: '2026-08-22 14:00', icon: 'validate' },
      { id: 'a4', action: 'Dossier clôturé', actor: 'Système', timestamp: '2026-08-22 16:00', icon: 'close' },
    ],
    processingTime: 7.0,
  },
  {
    id: 'd007',
    reference: 'QUO-2026-0067',
    title: "Devis — Travaux d'aménagement bureaux",
    type: 'quote',
    status: 'in_review',
    priority: 'high',
    sender: { name: 'BâtiPro Construction', type: 'supplier', avatarColor: 'bg-warning-600' },
    recipient: { name: 'Direction Générale', type: 'internal', avatarColor: 'bg-ink-700' },
    amount: 67500,
    currency: 'EUR',
    receivedDate: '2026-09-03',
    dueDate: '2026-09-13',
    aiSummary:
      "Devis de BâtiPro Construction pour l'aménagement des nouveaux bureaux du 4ème étage. Montant de 67 500 EUR, validité 10 jours. Les travaux incluent cloisonnement, électricité, peinture et mobilier. Délai d'exécution de 6 semaines après validation.",
    aiKeyPoints: [
      'Montant : 67 500 EUR',
      'Validité du devis : 10 jours',
      'Délai d\'exécution : 6 semaines',
      'Cloisonnement + électricité + peinture + mobilier',
      '3 devis concurrents suggérés pour comparaison',
    ],
    aiAmount: 67500,
    aiDueDate: '2026-09-13',
    aiConfidence: 89,
    aiSuggestedDepartment: 'Direction Générale',
    aiSuggestedAction: 'Comparer avec 3 devis concurrents et valider avant le 13 septembre.',
    assignedTo: 'Pierre Durand',
    assignedDepartment: 'Direction Générale',
    pages: 8,
    hasPhysicalOriginal: true,
    physicalStatus: 'in_transit',
    category: 'Devis',
    tags: ['devis', 'travaux', 'bureaux', 'à valider'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0139',
    projectId: 'proj002',
    collaboration: [
      {
        id: 'm1',
        author: 'Pierre Durand',
        authorRole: 'client',
        avatarColor: 'bg-accent-600',
        message: 'Pouvez-vous détailler le poste "mobilier" qui représente 22 000 EUR ?',
        timestamp: '2026-09-04 11:20',
      },
      {
        id: 'm2',
        author: 'Marc Petit',
        authorRole: 'supplier',
        avatarColor: 'bg-warning-600',
        message: 'Bien sûr, nous vous envoyons le détail du mobilier sélectionné avec les références.',
        timestamp: '2026-09-04 14:00',
        attachments: [{ name: 'detail-mobilier.pdf', type: 'pdf' }],
      },
    ],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-03 13:00', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Pierre Durand (DG)', actor: 'Auto-assignation', timestamp: '2026-09-03 13:05', icon: 'assign' },
      { id: 'a3', action: 'Échéance : 13 sept. 2026', actor: 'Système IA', timestamp: '2026-09-03 13:00', icon: 'alert' },
    ],
    processingTime: 3.1,
  },
  {
    id: 'd008',
    reference: 'DN-2026-0042',
    title: 'Bon de livraison — Marchandise import',
    type: 'delivery_note',
    status: 'validated',
    priority: 'normal',
    sender: { name: 'Global Logistics', type: 'supplier', avatarColor: 'bg-primary-600' },
    recipient: { name: 'Service Logistique', type: 'internal', avatarColor: 'bg-accent-600' },
    receivedDate: '2026-09-02',
    dueDate: '2026-09-02',
    aiSummary:
      "Bon de livraison de Global Logistics pour un import de marchandises. 15 palettes réceptionnées, conformes au bon de commande. Poids total 2,3 tonnes. Aucune réserve émise lors de la réception.",
    aiKeyPoints: [
      '15 palettes reçues',
      'Poids : 2,3 tonnes',
      'Conformité : OK',
      'Aucune réserve à la réception',
    ],
    aiConfidence: 98,
    aiSuggestedDepartment: 'Opérations',
    aiSuggestedAction: 'Vérifier la conformité et archiver le bon de livraison.',
    assignedTo: 'Julie Chen',
    assignedDepartment: 'Opérations',
    pages: 1,
    hasPhysicalOriginal: true,
    physicalStatus: 'delivered',
    category: 'Bon de livraison',
    tags: ['livraison', 'logistique', 'import'],
    direction: 'incoming',
    registerNumber: 'REG-E-2026-0137',
    collaboration: [],
    activity: [
      { id: 'a1', action: 'Document reçu et analysé par l\'IA', actor: 'Système IA', timestamp: '2026-09-02 07:30', icon: 'ai' },
      { id: 'a2', action: 'Affecté à Julie Chen (Opérations)', actor: 'Auto-assignation', timestamp: '2026-09-02 07:32', icon: 'assign' },
      { id: 'a3', action: 'Validé par Julie Chen', actor: 'Julie Chen', timestamp: '2026-09-02 09:00', icon: 'validate' },
    ],
    processingTime: 0.1,
  },
];

export const initialAssistantMessages: AssistantMessage[] = [
  {
    id: 'msg0',
    role: 'assistant',
    content:
      "Bonjour, je suis votre assistant documentaire. Je peux répondre à vos questions sur vos documents, échéances, statuts de traitement et bien plus. Que souhaitez-vous savoir ?",
    timestamp: '2026-09-06 08:00',
  },
];

export const assistantSuggestions = [
  'Quels documents arrivent à échéance cette semaine ?',
  'Montre-moi les factures de plus de 5 000 dollars non traitées',
  'Quels courriers attendent la validation du DG ?',
  'Où en est le dossier ABC ?',
  'Résume-moi ce contrat',
  'Quels services ont le plus de retard ?',
];

export const assistantResponses: Record<string, AssistantMessage> = {
  'Quels documents arrivent à échéance cette semaine ?': {
    id: 'resp1',
    role: 'assistant',
    content:
      '3 documents arrivent à échéance cette semaine. Voici le détail :',
    timestamp: '2026-09-06 08:01',
    data: {
      type: 'documents',
      items: [
        { label: 'Contrat — Cabinet Leroy & Associés', value: '10 sept. 2026', status: 'assigned' },
        { label: 'Devis — BâtiPro Construction', value: '13 sept. 2026', status: 'in_review' },
        { label: 'Bon de commande — Équipements réseau', value: '25 août 2026', status: 'overdue' },
      ],
    },
  },
  'Montre-moi les factures de plus de 5 000 dollars non traitées': {
    id: 'resp2',
    role: 'assistant',
    content:
      'J\'ai trouvé 3 factures de plus de 5 000 USD/EUR non encore traitées :',
    timestamp: '2026-09-06 08:02',
    data: {
      type: 'documents',
      items: [
        { label: 'INV-2026-0847 — TechnoSupply SARL', value: '12 500 USD', status: 'in_review' },
        { label: 'INV-2026-0848 — CloudSystems Inc.', value: '8 750 EUR', status: 'received' },
        { label: 'QUO-2026-0067 — BâtiPro Construction', value: '67 500 EUR', status: 'in_review' },
      ],
    },
  },
  'Quels courriers attendent la validation du DG ?': {
    id: 'resp3',
    role: 'assistant',
    content:
      '2 documents attendent actuellement la validation de Pierre Durand (DG) :',
    timestamp: '2026-09-06 08:03',
    data: {
      type: 'documents',
      items: [
        { label: 'Rapport mensuel — Activité commerciale', value: 'Reçu le 01/09', status: 'validated' },
        { label: 'Devis — Travaux d\'aménagement bureaux', value: 'Reçu le 03/09', status: 'in_review' },
      ],
    },
  },
  'Quels services ont le plus de retard ?': {
    id: 'resp4',
    role: 'assistant',
    content:
      'Voici le classement des services par nombre de documents en retard :',
    timestamp: '2026-09-06 08:04',
    data: {
      type: 'stats',
      items: [
        { label: 'Juridique', value: '6 documents en retard', status: 'overdue' },
        { label: 'Comptabilité', value: '5 documents en retard', status: 'overdue' },
        { label: 'Administration', value: '4 documents en retard', status: 'overdue' },
        { label: 'Commercial', value: '2 documents en retard', status: 'overdue' },
        { label: 'Opérations', value: '1 document en retard', status: 'overdue' },
      ],
    },
  },
  'Résume-moi ce contrat': {
    id: 'resp5',
    role: 'assistant',
    content:
      'Voici le résumé du contrat CTR-2026-0034 (Cabinet Leroy & Associés) : Contrat de prestation de conseil stratégique d\'une durée de 12 mois, renouvelable tacitement. Montant annuel de 85 000 EUR avec un préavis de résiliation de 3 mois. Le contrat inclut une clause de confidentialité renforcée et une exclusivité sectorielle. La signature est requise avant le 10 septembre 2026. La clause d\'exclusivité a été signalée comme potentiellement trop large par Sophie Martin (Juridique).',
    timestamp: '2026-09-06 08:05',
  },
  'Où en est le dossier ABC ?': {
    id: 'resp6',
    role: 'assistant',
    content:
      'Le dossier ABC correspond à la facture INV-2026-0847 (TechnoSupply SARL). Statut actuel : en cours de révision. Marie Dubois (Comptabilité) a identifié un écart de 625 USD avec le bon de commande. Le fournisseur a transmis le bon de livraison justificatif. Le document est en attente de validation comptable. Échéance le 30 septembre 2026.',
    timestamp: '2026-09-06 08:06',
  },
};

export const tasks: Task[] = [
  {
    id: 't001',
    title: 'Préparer le rapport mensuel de septembre',
    description: 'Consolider les données d\'activité du mois pour le rapport de direction.',
    status: 'in_progress',
    priority: 'high',
    assignedTo: 'Chantal Moreau',
    assignedDepartment: 'Administration',
    dueDate: '2026-09-12',
    createdDate: '2026-09-01',
    createdBy: 'Pierre Durand',
    project: 'Rapport septembre',
  },
  {
    id: 't002',
    title: 'Vérifier la conformité de la facture TechnoSupply',
    description: 'Comparer le montant avec le bon de commande PO-2026-0312 et valider le paiement.',
    status: 'assigned',
    priority: 'high',
    assignedTo: 'Marie Dubois',
    assignedDepartment: 'Comptabilité',
    dueDate: '2026-09-10',
    createdDate: '2026-09-04',
    createdBy: 'Système IA',
    sourceDocument: 'INV-2026-0847',
    project: 'Fournisseur ABC',
  },
  {
    id: 't003',
    title: 'Revoir les clauses du contrat Leroy & Associés',
    description: 'Analyser la clause d\'exclusivité et proposer une reformulation.',
    status: 'in_progress',
    priority: 'urgent',
    assignedTo: 'Sophie Martin',
    assignedDepartment: 'Juridique',
    dueDate: '2026-09-09',
    createdDate: '2026-09-05',
    createdBy: 'Pierre Durand',
    sourceDocument: 'CTR-2026-0034',
    project: 'Contrat conseil',
  },
  {
    id: 't004',
    title: 'Contacter Apex Industries pour échéancier',
    description: 'Négocier un plan de paiement suite à la mise en demeure reçue.',
    status: 'new',
    priority: 'urgent',
    assignedTo: 'Thomas Leroy',
    assignedDepartment: 'Juridique',
    dueDate: '2026-09-07',
    createdDate: '2026-09-06',
    createdBy: 'Système IA',
    sourceDocument: 'LTR-2026-0212',
  },
  {
    id: 't005',
    title: 'Comparer devis aménagement bureaux',
    description: 'Obtenir 2 devis concurrents supplémentaires et préparer un tableau comparatif.',
    status: 'assigned',
    priority: 'normal',
    assignedTo: 'Pierre Durand',
    assignedDepartment: 'Direction Générale',
    dueDate: '2026-09-13',
    createdDate: '2026-09-03',
    createdBy: 'Système IA',
    sourceDocument: 'QUO-2026-0067',
    project: 'Aménagement bureaux',
  },
  {
    id: 't006',
    title: 'Préparer la présentation trimestrielle',
    description: 'Synthèse Q3 pour le conseil d\'administration du 20 septembre.',
    status: 'submitted',
    priority: 'high',
    assignedTo: 'Chantal Moreau',
    assignedDepartment: 'Administration',
    dueDate: '2026-09-15',
    createdDate: '2026-08-20',
    createdBy: 'Pierre Durand',
    submittedDate: '2026-09-05',
    project: 'Rapport septembre',
  },
  {
    id: 't007',
    title: 'Mettre à jour le registre des fournisseurs',
    description: 'Ajouter les 3 nouveaux fournisseurs du trimestre et vérifier les informations fiscales.',
    status: 'closed',
    priority: 'low',
    assignedTo: 'Marie Dubois',
    assignedDepartment: 'Comptabilité',
    dueDate: '2026-08-30',
    createdDate: '2026-08-15',
    createdBy: 'Sophie Martin',
    validatedDate: '2026-08-28',
  },
  {
    id: 't008',
    title: 'Valider la livraison des équipements réseau',
    description: 'Confirmer la conformité des 12 commutateurs et 4 routeurs reçus.',
    status: 'closed',
    priority: 'normal',
    assignedTo: 'Julie Chen',
    assignedDepartment: 'Opérations',
    dueDate: '2026-08-25',
    createdDate: '2026-08-15',
    createdBy: 'Système IA',
    sourceDocument: 'ORD-2026-0156',
    validatedDate: '2026-08-22',
  },
];

export const dossiers: Dossier[] = [
  {
    id: 'dos001',
    name: 'Fournisseur TechnoSupply',
    status: 'active',
    documentCount: 18,
    documentBreakdown: { invoices: 6, contracts: 2, orders: 4, correspondence: 6, other: 0 },
    taskCount: 9,
    deadlineCount: 3,
    collaboratorCount: 5,
    tags: ['fournisseur', 'fournitures', 'Q3'],
    lastActivity: '2026-09-05',
  },
  {
    id: 'dos002',
    name: 'Contrat Cabinet Leroy',
    status: 'active',
    documentCount: 7,
    documentBreakdown: { invoices: 0, contracts: 2, orders: 0, correspondence: 5, other: 0 },
    taskCount: 3,
    deadlineCount: 1,
    collaboratorCount: 3,
    tags: ['contrat', 'juridique', 'conseil'],
    lastActivity: '2026-09-05',
  },
  {
    id: 'dos003',
    name: 'Apex Industries — Recouvrement',
    status: 'active',
    documentCount: 12,
    documentBreakdown: { invoices: 4, contracts: 1, orders: 0, correspondence: 7, other: 0 },
    taskCount: 5,
    deadlineCount: 2,
    collaboratorCount: 4,
    tags: ['client', 'recouvrement', 'juridique', 'urgent'],
    lastActivity: '2026-08-31',
  },
  {
    id: 'dos004',
    name: 'CloudSystems — Infrastructure',
    status: 'active',
    documentCount: 9,
    documentBreakdown: { invoices: 5, contracts: 1, orders: 0, correspondence: 3, other: 0 },
    taskCount: 2,
    deadlineCount: 1,
    collaboratorCount: 3,
    tags: ['IT', 'cloud', 'infrastructure'],
    lastActivity: '2026-09-06',
  },
  {
    id: 'dos005',
    name: 'Aménagement bureaux 4ème étage',
    status: 'active',
    documentCount: 6,
    documentBreakdown: { invoices: 0, contracts: 0, orders: 0, correspondence: 2, other: 4 },
    taskCount: 4,
    deadlineCount: 2,
    collaboratorCount: 6,
    tags: ['travaux', 'bureaux', 'projet'],
    lastActivity: '2026-09-04',
    projectId: 'proj002',
  },
];

export const projects: Project[] = [
  {
    id: 'proj001',
    name: 'Rapport consolidé Q3 2026',
    team: ['Pierre Durand', 'Chantal Moreau', 'Marie Dubois'],
    documentCount: 32,
    taskCount: 18,
    deadlineCount: 6,
    progress: 68,
    reportCount: 3,
    status: 'active',
    startDate: '2026-08-01',
  },
  {
    id: 'proj002',
    name: 'Aménagement bureaux 4ème étage',
    team: ['Pierre Durand', 'Julie Chen', 'Sophie Martin'],
    documentCount: 14,
    taskCount: 7,
    deadlineCount: 3,
    progress: 25,
    reportCount: 1,
    status: 'active',
    startDate: '2026-09-01',
    endDate: '2026-11-15',
  },
  {
    id: 'proj003',
    name: 'Audit fournisseurs 2026',
    team: ['Marie Dubois', 'Thomas Leroy'],
    documentCount: 47,
    taskCount: 12,
    deadlineCount: 4,
    progress: 45,
    reportCount: 2,
    status: 'active',
    startDate: '2026-07-15',
  },
];

export const reports: Report[] = [
  {
    id: 'rpt001',
    title: 'Rapport mensuel — Septembre 2026',
    period: 'Septembre 2026',
    status: 'collecting',
    createdDate: '2026-09-01',
    createdBy: 'Pierre Durand',
    contributions: [
      { id: 'c1', department: 'Finance', documentName: 'Rapport financier septembre', status: 'submitted', submittedDate: '2026-09-04', format: 'PDF + Excel' },
      { id: 'c2', department: 'Commercial', documentName: 'Chiffres septembre 2026', status: 'submitted', submittedDate: '2026-09-05', format: 'Excel' },
      { id: 'c3', department: 'Administration', documentName: 'Rapport d\'activité', status: 'pending', format: 'Word' },
      { id: 'c4', department: 'Opérations', documentName: 'Suivi des activités', status: 'submitted', submittedDate: '2026-09-03', format: 'PDF' },
    ],
    sections: [
      { title: 'Résumé exécutif', status: 'pending' },
      { title: 'Activités réalisées', status: 'ready' },
      { title: 'Résultats', status: 'ready' },
      { title: 'Difficultés', status: 'pending' },
      { title: 'Échéances', status: 'pending' },
      { title: 'Activités en retard', status: 'pending' },
      { title: 'Recommandations', status: 'pending' },
      { title: 'Priorités du prochain mois', status: 'pending' },
    ],
  },
  {
    id: 'rpt002',
    title: 'Rapport trimestriel Q3 2026',
    period: 'Juillet - Septembre 2026',
    status: 'review',
    createdDate: '2026-09-02',
    createdBy: 'Pierre Durand',
    contributions: [
      { id: 'c1', department: 'Finance', documentName: 'Bilan financier Q3', status: 'submitted', submittedDate: '2026-09-01', format: 'PDF' },
      { id: 'c2', department: 'Commercial', documentName: 'Résultats commerciaux Q3', status: 'submitted', submittedDate: '2026-09-02', format: 'Excel' },
      { id: 'c3', department: 'Administration', documentName: 'Synthèse administrative Q3', status: 'submitted', submittedDate: '2026-09-03', format: 'Word' },
      { id: 'c4', department: 'Opérations', documentName: 'Rapport opérations Q3', status: 'submitted', submittedDate: '2026-09-04', format: 'PDF' },
    ],
    aiSummary: 'Le T3 2026 montre une croissance de 12% du chiffre d\'affaires. 286 documents traités avec un taux de respect des délais de 87%. Trois projets actifs progressent conformément aux prévisions. Le département Juridique présente 6 documents en retard nécessitant une attention particulière. Recommandation : renforcer l\'équipe Grand Comptes et accélérer le traitement des dossiers de recouvrement.',
    sections: [
      { title: 'Résumé exécutif', content: 'Croissance de 12% au T3 2026. 286 documents traités à 87% dans les délais.', status: 'ready' },
      { title: 'Activités réalisées', content: '47 nouveaux contrats signés. 3 projets actifs. Audit fournisseurs à 45% de progression.', status: 'ready' },
      { title: 'Résultats', content: 'CA trimestriel : 3,6M EUR. Taux de conversion : 23%. Marge opérationnelle : 18%.', status: 'ready' },
      { title: 'Difficultés', content: 'Retard de traitement au Juridique (6 dossiers). Recouvrement Apex Industries en souffrance.', status: 'ready' },
      { title: 'Échéances', content: '10 échéances au total pour le T3, 8 respectées, 2 en retard.', status: 'ready' },
      { title: 'Recommandations', content: 'Renforcer l\'équipe Grand Comptes. Accélérer le recouvrement. Digitaliser les processus juridiques.', status: 'ready' },
      { title: 'Priorités T4', content: 'Finaliser l\'aménagement des bureaux. Clôturer le recouvrement Apex. Préparer le budget 2027.', status: 'ready' },
    ],
  },
];

export const teamMembers: TeamMember[] = [
  { id: 'u001', name: 'Pierre Durand', role: 'dg', roleLabel: 'Directeur Général', department: 'Direction Générale', email: 'p.durand@entreprise.com', avatarColor: 'bg-ink-700', lastActive: 'En ligne', documentCount: 42, taskCount: 8 },
  { id: 'u002', name: 'Marie Dubois', role: 'manager', roleLabel: 'Manager Finance', department: 'Comptabilité', email: 'm.dubois@entreprise.com', avatarColor: 'bg-accent-600', lastActive: 'Il y a 5 min', documentCount: 94, taskCount: 12 },
  { id: 'u003', name: 'Sophie Martin', role: 'manager', roleLabel: 'Manager Juridique', department: 'Juridique', email: 's.martin@entreprise.com', avatarColor: 'bg-primary-600', lastActive: 'Il y a 1h', documentCount: 43, taskCount: 6 },
  { id: 'u004', name: 'Thomas Leroy', role: 'collaborator', roleLabel: 'Collaborateur Juridique', department: 'Juridique', email: 't.leroy@entreprise.com', avatarColor: 'bg-danger-600', lastActive: 'Il y a 3h', documentCount: 28, taskCount: 5 },
  { id: 'u005', name: 'Chantal Moreau', role: 'manager', roleLabel: 'Manager Administration', department: 'Administration', email: 'c.moreau@entreprise.com', avatarColor: 'bg-warning-600', lastActive: 'En ligne', documentCount: 67, taskCount: 9 },
  { id: 'u006', name: 'Julie Chen', role: 'collaborator', roleLabel: 'Collaboratrice Opérations', department: 'Opérations', email: 'j.chen@entreprise.com', avatarColor: 'bg-primary-500', lastActive: 'Il y a 30 min', documentCount: 30, taskCount: 4 },
  { id: 'u007', name: 'Karim Benali', role: 'external', roleLabel: 'Fournisseur — TechnoSupply', department: 'Externe', email: 'k.benali@technosupply.com', avatarColor: 'bg-primary-600', lastActive: 'Il y a 2 jours', documentCount: 6, taskCount: 0 },
];

export const rolePermissions: RolePermission[] = [
  {
    role: 'super_admin',
    roleLabel: 'Super Admin',
    description: 'Gestion complète de l\'entreprise et de la plateforme.',
    userCount: 1,
    permissions: [
      { label: 'Gérer l\'entreprise et les utilisateurs', granted: true },
      { label: 'Configurer les rôles et permissions', granted: true },
      { label: 'Vue globale tous départements', granted: true },
      { label: 'Valider et clôturer', granted: true },
      { label: 'Archivage et suppression', granted: true },
      { label: 'Paramètres système', granted: true },
    ],
  },
  {
    role: 'dg',
    roleLabel: 'DG / Direction',
    description: 'Vue globale de l\'entreprise et validations de haut niveau.',
    userCount: 2,
    permissions: [
      { label: 'Vue globale tous départements', granted: true },
      { label: 'Valider et clôturer', granted: true },
      { label: 'Créer tâches et projets', granted: true },
      { label: 'Rapports consolidés', granted: true },
      { label: 'Archivage', granted: true },
      { label: 'Gérer les utilisateurs', granted: false },
    ],
  },
  {
    role: 'manager',
    roleLabel: 'Manager',
    description: 'Gestion de son équipe et des dossiers de son département.',
    userCount: 3,
    permissions: [
      { label: 'Vue département et équipe', granted: true },
      { label: 'Affecter des tâches', granted: true },
      { label: 'Valider le travail de son équipe', granted: true },
      { label: 'Créer des dossiers', granted: true },
      { label: 'Vue globale autres départements', granted: false },
      { label: 'Gérer les utilisateurs', granted: false },
    ],
  },
  {
    role: 'collaborator',
    roleLabel: 'Collaborateur',
    description: 'Accès aux documents et tâches qui lui sont affectés.',
    userCount: 8,
    permissions: [
      { label: 'Documents et tâches assignés', granted: true },
      { label: 'Collaborer sur les documents', granted: true },
      { label: 'Soumettre son travail', granted: true },
      { label: 'Valider', granted: false },
      { label: 'Affecter à d\'autres', granted: false },
      { label: 'Archiver', granted: false },
    ],
  },
  {
    role: 'external',
    roleLabel: 'Externe (B2B)',
    description: 'Accès uniquement aux documents B2B partagés.',
    userCount: 12,
    permissions: [
      { label: 'Documents B2B partagés', granted: true },
      { label: 'Discussion sur documents partagés', granted: true },
      { label: 'Voir informations internes', granted: false },
      { label: 'Accès autres documents', granted: false },
      { label: 'Tâches internes', granted: false },
      { label: 'Archivage', granted: false },
    ],
  },
];

export const escalationRules: EscalationRule[] = [
  { id: 'er1', trigger: 'J-7 avant échéance', action: 'Rappel au responsable + manager', timing: '7 jours avant', active: true },
  { id: 'er2', trigger: 'J-3 avant échéance', action: 'Rappel + notification dashboard', timing: '3 jours avant', active: true },
  { id: 'er3', trigger: 'J-1 avant échéance', action: 'Alerte urgente au responsable + DG', timing: '1 jour avant', active: true },
  { id: 'er4', trigger: 'Jour J', action: 'Échéance aujourd\'hui — notification prioritaire', timing: 'Le jour même', active: true },
  { id: 'er5', trigger: 'J+1 après échéance', action: 'Document marqué en retard + escalade DG', timing: '1 jour après', active: true },
];

export const rfqTemplates: RFQTemplate[] = [
  { id: 'tpl1', name: 'Achat de marchandises', icon: 'Package', description: 'Achat de biens et fournitures avec tableau de produits.', category: 'Achats', fieldCount: 8, productCount: 5 },
  { id: 'tpl2', name: 'Matériel informatique', icon: 'Laptop', description: 'Ordinateurs, écrans, périphériques avec spécifications techniques.', category: 'IT', fieldCount: 12, productCount: 3 },
  { id: 'tpl3', name: 'Location véhicule', icon: 'Car', description: 'Location de véhicules avec durée, kilometrage et assurance.', category: 'Logistique', fieldCount: 6, productCount: 2 },
  { id: 'tpl4', name: 'Travaux de construction', icon: 'HardHat', description: 'Travaux, matériaux et main d\'oeuvre avec planning.', category: 'Construction', fieldCount: 10, productCount: 8 },
  { id: 'tpl5', name: 'Prestations de services', icon: 'Briefcase', description: 'Services professionnels avec livrables et SLA.', category: 'Services', fieldCount: 7, productCount: 0 },
  { id: 'tpl6', name: 'Transport / Logistique', icon: 'Truck', description: 'Transport de marchandises avec itinéraires et délais.', category: 'Logistique', fieldCount: 5, productCount: 0 },
  { id: 'tpl7', name: 'Fournitures de bureau', icon: 'Printer', description: 'Papeterie, consommables et matériel de bureau.', category: 'Achats', fieldCount: 6, productCount: 10 },
];

export const rfqs: RFQ[] = [
  {
    id: 'rfq1',
    reference: 'RFQ-2026-0045',
    title: 'Fourniture d\'ordinateurs portables',
    status: 'closed',
    createdBy: 'Marie Dubois',
    createdDate: '2026-09-01',
    deadline: '2026-09-20',
    deliveryLocation: 'Kinshasa',
    description: 'Acquisition de 20 ordinateurs portables Core i7 pour le personnel, avec écrans et docks USB-C. Cahier des charges joint.',
    hasAttachment: true,
    attachmentName: 'Cahier-des-charges-RFQ-0045.pdf',
    products: [
      { id: 'p1', product: 'Laptop Core i7', quantity: 20, specifications: '16GB / 512GB SSD', supplierFilled: true },
      { id: 'p2', product: 'Écran 24"', quantity: 20, specifications: 'Full HD', supplierFilled: true },
      { id: 'p3', product: 'Dock USB-C', quantity: 20, specifications: 'Universel', supplierFilled: true },
    ],
    formFields: [
      { id: 'f1', type: 'radio', label: 'Quelle est votre durée de garantie ?', required: true, options: ['6 mois', '12 mois', '24 mois', 'Autre'] },
      { id: 'f2', type: 'number', label: 'Quel est votre délai de livraison ?', required: true, placeholder: 'jours', helpText: 'En jours ouvrés' },
      { id: 'f3', type: 'textarea', label: 'Conditions de paiement proposées', required: true },
      { id: 'f4', type: 'boolean', label: 'Le produit est-il disponible immédiatement ?', required: true },
      { id: 'f5', type: 'file', label: 'Joindre votre facture proforma', required: true, helpText: 'Format PDF' },
      { id: 'f6', type: 'text', label: 'Marque proposée', required: false },
    ],
    submissions: [
      {
        id: 's1',
        supplierName: 'CongoTech',
        supplierAvatarColor: 'bg-primary-600',
        status: 'submitted',
        submittedDate: '2026-09-18',
        totalAmount: 17900,
        currency: 'USD',
        deliveryDays: 14,
        warranty: '12 mois',
        paymentTerms: '100% à la livraison',
        availability: true,
        technicalConformity: 92,
        documentsComplete: true,
        proformaAmount: 17900,
        productPrices: [
          { productId: 'p1', unitPrice: 650, totalPrice: 13000 },
          { productId: 'p2', unitPrice: 180, totalPrice: 3600 },
          { productId: 'p3', unitPrice: 65, totalPrice: 1300 },
        ],
        fieldResponses: [
          { fieldId: 'f1', value: '12 mois' },
          { fieldId: 'f2', value: '14' },
          { fieldId: 'f3', value: '100% à la livraison' },
          { fieldId: 'f4', value: 'Oui' },
          { fieldId: 'f6', value: 'Dell' },
        ],
        score: 82,
      },
      {
        id: 's2',
        supplierName: 'ABC Tech',
        supplierAvatarColor: 'bg-accent-600',
        status: 'submitted',
        submittedDate: '2026-09-17',
        totalAmount: 18500,
        currency: 'USD',
        deliveryDays: 7,
        warranty: '12 mois',
        paymentTerms: '50% commande / 50% livraison',
        availability: true,
        technicalConformity: 96,
        documentsComplete: false,
        proformaAmount: 19250,
        hasDiscrepancy: true,
        discrepancyDetail: 'Le fournisseur a indiqué 18 500 $ dans le formulaire, mais la facture proforma jointe indique 19 250 $.',
        productPrices: [
          { productId: 'p1', unitPrice: 680, totalPrice: 13600 },
          { productId: 'p2', unitPrice: 195, totalPrice: 3900 },
          { productId: 'p3', unitPrice: 50, totalPrice: 1000 },
        ],
        fieldResponses: [
          { fieldId: 'f1', value: '12 mois' },
          { fieldId: 'f2', value: '7' },
          { fieldId: 'f3', value: '50% commande / 50% livraison' },
          { fieldId: 'f4', value: 'Oui' },
          { fieldId: 'f6', value: 'HP' },
        ],
        score: 86,
      },
      {
        id: 's3',
        supplierName: 'DigitalPro',
        supplierAvatarColor: 'bg-warning-600',
        status: 'submitted',
        submittedDate: '2026-09-16',
        totalAmount: 19200,
        currency: 'USD',
        deliveryDays: 5,
        warranty: '24 mois',
        paymentTerms: '30 jours net',
        availability: true,
        technicalConformity: 100,
        documentsComplete: true,
        proformaAmount: 19200,
        productPrices: [
          { productId: 'p1', unitPrice: 700, totalPrice: 14000 },
          { productId: 'p2', unitPrice: 210, totalPrice: 4200 },
          { productId: 'p3', unitPrice: 50, totalPrice: 1000 },
        ],
        fieldResponses: [
          { fieldId: 'f1', value: '24 mois' },
          { fieldId: 'f2', value: '5' },
          { fieldId: 'f3', value: '30 jours net' },
          { fieldId: 'f4', value: 'Oui' },
          { fieldId: 'f6', value: 'Lenovo' },
        ],
        score: 91,
      },
    ],
    scoringCriteria: [
      { label: 'Prix', weight: 30 },
      { label: 'Délai de livraison', weight: 20 },
      { label: 'Conformité technique', weight: 25 },
      { label: 'Garantie', weight: 10 },
      { label: 'Conditions de paiement', weight: 10 },
      { label: 'Disponibilité', weight: 5 },
    ],
    aiRecommendedSupplierId: 's3',
    aiRecommendationReason: 'DigitalPro obtient le meilleur score selon les critères définis pour cette consultation. Son offre n\'est pas la moins chère, mais elle présente la meilleure conformité technique, le délai de livraison le plus court et une garantie de 24 mois.',
  },
  {
    id: 'rfq2',
    reference: 'RFQ-2026-0046',
    title: 'Prestations de nettoyage bureaux',
    status: 'open',
    createdBy: 'Chantal Moreau',
    createdDate: '2026-09-03',
    deadline: '2026-09-25',
    deliveryLocation: 'Kinshasa',
    description: 'Prestations de nettoyage quotidien pour les bureaux des 3ème et 4ème étages. Contrat de 12 mois renouvelable.',
    hasAttachment: true,
    attachmentName: 'Spec-nettoyage.pdf',
    products: [],
    formFields: [
      { id: 'f1', type: 'number', label: 'Nombre d\'agents proposés', required: true },
      { id: 'f2', type: 'textarea', label: 'Produits et équipements fournis', required: true },
      { id: 'f3', type: 'currency', label: 'Coût mensuel proposé', required: true },
      { id: 'f4', type: 'select', label: 'Fréquence des prestations', required: true, options: ['Quotidien', '2x/semaine', 'Hebdomadaire'] },
      { id: 'f5', type: 'file', label: 'Joindre votre offre technique', required: true },
    ],
    submissions: [
      {
        id: 's4',
        supplierName: 'CleanPro Services',
        supplierAvatarColor: 'bg-accent-600',
        status: 'submitted',
        submittedDate: '2026-09-05',
        totalAmount: 2400,
        currency: 'USD',
        deliveryDays: 0,
        warranty: 'N/A',
        paymentTerms: 'Mensuel',
        availability: true,
        technicalConformity: 88,
        documentsComplete: true,
        proformaAmount: 2400,
        productPrices: [],
        fieldResponses: [
          { fieldId: 'f1', value: '4 agents' },
          { fieldId: 'f4', value: 'Quotidien' },
          { fieldId: 'f3', value: '2400' },
        ],
        score: 78,
      },
    ],
    scoringCriteria: [
      { label: 'Prix', weight: 35 },
      { label: 'Qualité de service', weight: 30 },
      { label: 'Disponibilité', weight: 20 },
      { label: 'Conditions de paiement', weight: 15 },
    ],
  },
  {
    id: 'rfq3',
    reference: 'RFQ-2026-0047',
    title: 'Location véhicules de fonction',
    status: 'published',
    createdBy: 'Julie Chen',
    createdDate: '2026-09-05',
    deadline: '2026-09-30',
    deliveryLocation: 'Kinshasa',
    description: 'Location de 5 véhicules de fonction avec chauffeur pour une durée de 6 mois.',
    hasAttachment: false,
    products: [
      { id: 'p1', product: 'Berline diesel', quantity: 3, specifications: 'Automatique, climatisée', supplierFilled: true },
      { id: 'p2', product: 'SUV', quantity: 2, specifications: '4x4, 7 places', supplierFilled: true },
    ],
    formFields: [
      { id: 'f1', type: 'number', label: 'Kilometrage mensuel inclus', required: true },
      { id: 'f2', type: 'boolean', label: 'Chauffeur inclus ?', required: true },
      { id: 'f3', type: 'currency', label: 'Tarif mensuel par véhicule', required: true },
      { id: 'f4', type: 'radio', label: 'Assurance incluse ?', required: true, options: ['Oui, tous risques', 'Oui, au tiers', 'Non'] },
      { id: 'f5', type: 'file', label: 'Joindre votre catalogue', required: false },
    ],
    submissions: [],
    scoringCriteria: [
      { label: 'Prix', weight: 40 },
      { label: 'Qualité des véhicules', weight: 25 },
      { label: 'Conditions', weight: 20 },
      { label: 'Assurance', weight: 15 },
    ],
  },
];

// ===== B2B Network Data =====

export const networkCompanies: Company[] = [
  {
    id: 'co-1',
    name: 'CongoTech SARL',
    logoColor: 'bg-primary-600',
    address: '12 Boulevard du 30 Juin',
    city: 'Kinshasa',
    country: 'RDC',
    phone: '+243 81 234 5678',
    email: 'contact@congotech.cd',
    taxId: 'RCCM-KIN-2019-0042',
    sectors: ['Informatique', 'Électronique'],
    productsServices: ['Ordinateurs portables', 'Serveurs', 'Réseaux', 'Maintenance IT'],
    contactPersons: [
      { name: 'Karim Benali', role: 'Directeur Commercial', email: 'karim@congotech.cd', phone: '+243 81 234 5678' },
    ],
    docFlowCode: 'DF-CT-83921',
    status: 'verified',
    servedZones: ['Kinshasa', 'Lubumbashi'],
    categories: ['Informatique', 'Électronique'],
  },
  {
    id: 'co-2',
    name: 'ABC Construction',
    logoColor: 'bg-warning-600',
    address: '45 Av. de la Justice',
    city: 'Lubumbashi',
    country: 'RDC',
    phone: '+243 99 876 5432',
    email: 'info@abcconstruction.cd',
    taxId: 'RCCM-LUB-2017-0156',
    sectors: ['Construction', 'BTP'],
    productsServices: ['Matériaux de construction', 'Travaux publics', 'Génie civil'],
    contactPersons: [
      { name: 'Jean-Marc Kabongo', role: 'DG', email: 'jmk@abcconstruction.cd', phone: '+243 99 876 5432' },
    ],
    docFlowCode: 'DF-ABC-47291',
    status: 'verified',
    servedZones: ['Lubumbashi', 'Kinshasa', 'Goma'],
    categories: ['Construction', 'BTP'],
  },
  {
    id: 'co-3',
    name: 'Logistique Plus',
    logoColor: 'bg-accent-600',
    address: '78 Rue Mukalla',
    city: 'Kinshasa',
    country: 'RDC',
    phone: '+243 82 345 6789',
    email: 'service@logistiqueplus.cd',
    taxId: 'RCCM-KIN-2020-0387',
    sectors: ['Transport', 'Logistique'],
    productsServices: ['Transport de marchandises', 'Location de véhicules', 'Messagerie'],
    contactPersons: [
      { name: 'Aminata Diallo', role: 'Responsable Commercial', email: 'aminata@logistiqueplus.cd', phone: '+243 82 345 6789' },
    ],
    docFlowCode: 'DF-LP-61583',
    status: 'verified',
    servedZones: ['Kinshasa', 'Goma', 'Lubumbashi', 'Matadi'],
    categories: ['Transport', 'Logistique'],
  },
  {
    id: 'co-4',
    name: 'Digital Solutions',
    logoColor: 'bg-danger-600',
    address: '23 Av. Kasa-Vubu',
    city: 'Kinshasa',
    country: 'RDC',
    phone: '+243 81 456 7890',
    email: 'hello@digitalsolutions.cd',
    taxId: 'RCCM-KIN-2021-0512',
    sectors: ['Informatique', 'Télécoms'],
    productsServices: ['Développement web', 'Sécurité réseau', 'Cloud', 'Formation IT'],
    contactPersons: [
      { name: 'Patrick Mwamba', role: 'CTO', email: 'patrick@digitalsolutions.cd', phone: '+243 81 456 7890' },
    ],
    docFlowCode: 'DF-DS-92487',
    status: 'unverified',
    servedZones: ['Kinshasa'],
    categories: ['Informatique', 'Télécoms'],
  },
  {
    id: 'co-5',
    name: 'TechnoSupply SARL',
    logoColor: 'bg-ink-700',
    address: '56 Boulevard Kasa-Vubu',
    city: 'Kinshasa',
    country: 'RDC',
    phone: '+243 99 123 4567',
    email: 'ventes@technosupply.cd',
    taxId: 'RCCM-KIN-2018-0098',
    sectors: ['Fournitures de bureau', 'Électronique'],
    productsServices: ['Fournitures de bureau', 'Cartouches imprimante', 'Petit matériel'],
    contactPersons: [
      { name: 'Karim Benali', role: 'Commercial', email: 'karim@technosupply.cd', phone: '+243 99 123 4567' },
    ],
    docFlowCode: 'DF-TS-38174',
    status: 'verified',
    servedZones: ['Kinshasa', 'Lubumbashi'],
    categories: ['Fournitures de bureau', 'Électronique'],
  },
  {
    id: 'co-6',
    name: 'Mobilier Pro',
    logoColor: 'bg-primary-500',
    address: '34 Rue de l\'Échangeur',
    city: 'Goma',
    country: 'RDC',
    phone: '+243 82 567 8901',
    email: 'contact@mobilierpro.cd',
    taxId: 'RCCM-GOM-2022-0234',
    sectors: ['Mobilier', 'Aménagement'],
    productsServices: ['Mobilier de bureau', 'Chaises ergonomiques', 'Aménagement d\'espaces'],
    contactPersons: [
      { name: 'Esther Nzigama', role: 'Gérante', email: 'esther@mobilierpro.cd', phone: '+243 82 567 8901' },
    ],
    docFlowCode: 'DF-MP-73219',
    status: 'verified',
    servedZones: ['Goma', 'Kinshasa'],
    categories: ['Mobilier', 'Aménagement'],
  },
  {
    id: 'co-7',
    name: 'Clean Services Express',
    logoColor: 'bg-accent-500',
    address: '89 Av. du Commerce',
    city: 'Kinshasa',
    country: 'RDC',
    phone: '+243 81 678 9012',
    email: 'info@cleanservices.cd',
    taxId: 'RCCM-KIN-2023-0678',
    sectors: ['Services', 'Nettoyage'],
    productsServices: ['Nettoyage bureaux', 'Entretien espaces verts', 'Désinfection'],
    contactPersons: [
      { name: 'Joseph Mobati', role: 'Directeur', email: 'joseph@cleanservices.cd', phone: '+243 81 678 9012' },
    ],
    docFlowCode: 'DF-CSE-51847',
    status: 'unverified',
    servedZones: ['Kinshasa'],
    categories: ['Services', 'Nettoyage'],
  },
  {
    id: 'co-8',
    name: 'MediPlus Distribution',
    logoColor: 'bg-warning-500',
    address: '12 Av. de l\'Hôpital',
    city: 'Lubumbashi',
    country: 'RDC',
    phone: '+243 99 789 0123',
    email: 'commandes@mediplus.cd',
    taxId: 'RCCM-LUB-2016-0143',
    sectors: ['Médical', 'Pharmaceutique'],
    productsServices: ['Équipement médical', 'Fournitures pharmaceutiques', 'Laboratoire'],
    contactPersons: [
      { name: 'Dr. Alice Mukendi', role: 'Directrice Générale', email: 'alice@mediplus.cd', phone: '+243 99 789 0123' },
    ],
    docFlowCode: 'DF-MPD-29564',
    status: 'verified',
    servedZones: ['Lubumbashi', 'Kinshasa'],
    categories: ['Médical', 'Pharmaceutique'],
  },
];

export const partners: Partner[] = [
  {
    id: 'pt-1',
    company: networkCompanies[4],
    relation: 'supplier',
    status: 'active',
    addedDate: '2026-01-15',
    notes: 'Fournisseur principal de fournitures de bureau. Délais respectés.',
    favorite: true,
    isDocFlowMember: true,
  },
  {
    id: 'pt-2',
    company: networkCompanies[2],
    relation: 'both',
    status: 'active',
    addedDate: '2026-02-10',
    notes: 'Partenaire logistique. Nous leur envoyons aussi des documents.',
    favorite: false,
    isDocFlowMember: true,
  },
  {
    id: 'pt-3',
    company: networkCompanies[0],
    relation: 'supplier',
    status: 'active',
    addedDate: '2026-03-05',
    notes: 'Équipement IT. Bon rapport qualité-prix.',
    favorite: true,
    isDocFlowMember: true,
  },
  {
    id: 'pt-4',
    company: networkCompanies[1],
    relation: 'customer',
    status: 'active',
    addedDate: '2026-01-20',
    notes: 'Client pour prestations de conseil en gestion de projets.',
    favorite: false,
    isDocFlowMember: true,
  },
  {
    id: 'pt-5',
    company: networkCompanies[3],
    relation: 'supplier',
    status: 'invited',
    addedDate: '2026-09-01',
    notes: 'Invité à rejoindre Registre intelligent. En attente d\'inscription.',
    favorite: false,
    isDocFlowMember: false,
    invitedDate: '2026-09-01',
  },
  {
    id: 'pt-6',
    company: networkCompanies[5],
    relation: 'supplier',
    status: 'active',
    addedDate: '2026-04-12',
    notes: 'Mobilier de bureau. Livraison Goma et Kinshasa.',
    favorite: false,
    isDocFlowMember: true,
  },
  {
    id: 'pt-7',
    company: networkCompanies[6],
    relation: 'supplier',
    status: 'pending',
    addedDate: '2026-08-28',
    notes: 'Prestation de nettoyage. Demande de cotation en cours.',
    favorite: false,
    isDocFlowMember: false,
  },
  {
    id: 'pt-8',
    company: networkCompanies[7],
    relation: 'customer',
    status: 'active',
    addedDate: '2026-05-03',
    notes: 'Client pour la distribution de matériel médical.',
    favorite: false,
    isDocFlowMember: true,
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'op-1',
    reference: 'RFQ-7K42M',
    title: '20 laptops Core i7 pour personnel',
    clientName: 'XYZ SARL',
    clientLogoColor: 'bg-primary-600',
    deadline: '2026-09-15',
    status: 'to_answer',
    mode: 'private',
    description: 'Recherche de 20 ordinateurs portables Core i7, 16GB RAM, 512GB SSD pour équiper le personnel.',
    products: [
      { name: 'Laptop Core i7', quantity: 20, specifications: '16GB / 512GB SSD' },
    ],
    hasForm: true,
    currency: 'USD',
  },
  {
    id: 'op-2',
    reference: 'RFQ-9X31P',
    title: '100 chaises de bureau ergonomiques',
    clientName: 'ABC SA',
    clientLogoColor: 'bg-warning-600',
    deadline: '2026-09-18',
    status: 'submitted',
    mode: 'private',
    description: 'Fourniture de 100 chaises de bureau ergonomiques avec accoudoirs réglables.',
    products: [
      { name: 'Chaise ergonomique', quantity: 100, specifications: 'Accoudoirs réglables, dossier mesh' },
    ],
    hasForm: true,
    submittedDate: '2026-09-03',
    submittedAmount: 12500,
    currency: 'USD',
  },
  {
    id: 'op-3',
    reference: 'RFQ-5B82Q',
    title: 'Transport de marchandises Goma',
    clientName: 'DEF SARL',
    clientLogoColor: 'bg-accent-600',
    deadline: '2026-09-22',
    status: 'new',
    mode: 'open',
    description: 'Recherche de transporteur pour acheminer 15 tonnes de marchandises vers Goma.',
    products: [
      { name: 'Transport 15t', quantity: 1, specifications: 'Kinshasa → Goma, délai 5 jours' },
    ],
    hasForm: true,
    currency: 'USD',
  },
  {
    id: 'op-4',
    reference: 'RFQ-3M67T',
    title: 'Fournitures de bureau Q4',
    clientName: 'TechnoSupply SARL',
    clientLogoColor: 'bg-ink-700',
    deadline: '2026-08-28',
    status: 'awarded',
    mode: 'private',
    description: 'Fournitures de bureau pour le quatrième trimestre. Ramettes, cartouches, petit matériel.',
    products: [
      { name: 'Ramette A4 80g', quantity: 200, specifications: 'Boîte de 5' },
      { name: 'Cartouche imprimante', quantity: 30, specifications: 'Compatibles HP' },
    ],
    hasForm: true,
    submittedDate: '2026-08-20',
    submittedAmount: 3400,
    currency: 'USD',
    awardAmount: 3400,
  },
  {
    id: 'op-5',
    reference: 'RFQ-1A94Z',
    title: 'Aménagement open-space 200m²',
    clientName: 'InnovCorp',
    clientLogoColor: 'bg-danger-600',
    deadline: '2026-09-10',
    status: 'rejected',
    mode: 'open',
    description: 'Aménagement d\'un open-space de 200m² avec bureaux, cloisons et mobilier.',
    products: [
      { name: 'Bureau open-space', quantity: 15, specifications: 'Plateau 160x80cm' },
      { name: 'Cloison acoustique', quantity: 8, specifications: 'Hauteur 120cm' },
    ],
    hasForm: true,
    submittedDate: '2026-09-02',
    submittedAmount: 18500,
    currency: 'USD',
  },
  {
    id: 'op-6',
    reference: 'RFQ-6F28L',
    title: 'Maintenance préventive serveurs',
    clientName: 'CloudSystems Inc.',
    clientLogoColor: 'bg-primary-500',
    deadline: '2026-09-25',
    status: 'to_answer',
    mode: 'private',
    description: 'Contrat de maintenance préventive annuelle pour 12 serveurs.',
    products: [
      { name: 'Maintenance serveur', quantity: 12, specifications: 'Visite mensuelle, support 24/7' },
    ],
    hasForm: true,
    currency: 'USD',
  },
];
